// <auto-generated />
using System;
using DesafioFastBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DesafioFastBack.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316184202_InicialPostgres")]
    partial class InicialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DesafioFastBack.Models.Ata", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("workshopId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("workshopId");

                    b.ToTable("Atas");
                });

            modelBuilder.Entity("DesafioFastBack.Models.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AtaId")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AtaId");

                    b.ToTable("Colaboradores");
                });

            modelBuilder.Entity("DesafioFastBack.Models.Workshop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataRealizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Workshops");
                });

            modelBuilder.Entity("DesafioFastBack.Models.Ata", b =>
                {
                    b.HasOne("DesafioFastBack.Models.Workshop", "workshop")
                        .WithMany()
                        .HasForeignKey("workshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("workshop");
                });

            modelBuilder.Entity("DesafioFastBack.Models.Colaborador", b =>
                {
                    b.HasOne("DesafioFastBack.Models.Ata", null)
                        .WithMany("Colaborador")
                        .HasForeignKey("AtaId");
                });

            modelBuilder.Entity("DesafioFastBack.Models.Ata", b =>
                {
                    b.Navigation("Colaborador");
                });
#pragma warning restore 612, 618
        }
    }
}
